/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adhoc;

import java.util.Random;

/**
 *
 * @author hp probook
 */
public class Param extends javax.swing.JFrame {
static Random rnd = new Random();
    /**
     * Creates new form Param
     */
    public Param() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lambda = new javax.swing.JTextField();
        Tsim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        vw1 = new javax.swing.JTextField();
        vw2 = new javax.swing.JTextField();
        vw3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        vw4 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        DL = new javax.swing.JTextField();
        LAV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        rtmax = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        densite = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        w1 = new javax.swing.JTextField();
        w2 = new javax.swing.JTextField();
        w3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rc = new javax.swing.JTextField();
        rr = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Poisson Law Distribution ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setText("Lambda :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 30, 70, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel3.setText("sec");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(280, 60, 40, 14);

        lambda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lambda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lambda.setText("5");
        jPanel2.add(lambda);
        lambda.setBounds(180, 30, 90, 20);

        Tsim.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Tsim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tsim.setText("300");
        jPanel2.add(Tsim);
        Tsim.setBounds(180, 50, 90, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel4.setText("Simulation time :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 60, 130, 14);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(370, 10, 360, 90);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 500, 140, 23);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Damping Factors ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("a :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(70, 70, 80, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Th :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(70, 40, 90, 20);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0.90");
        jPanel3.add(jTextField6);
        jTextField6.setBounds(160, 70, 70, 20);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("10");
        jPanel3.add(jTextField7);
        jTextField7.setBounds(160, 100, 70, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Nb. Iter :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(70, 100, 90, 20);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("8");
        jPanel3.add(jTextField8);
        jTextField8.setBounds(160, 40, 70, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel14.setText("sec");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(240, 40, 40, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(370, 110, 360, 180);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Fitness Clustering Parameters ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("AVI :");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 30, 40, 20);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("3");
        jPanel4.add(jTextField1);
        jTextField1.setBounds(90, 30, 70, 20);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Adjustment Factors ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel7.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Beta :");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(20, 60, 60, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Sigma :");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(170, 60, 50, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Alpha :");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(20, 30, 60, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Gamma :");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(170, 30, 50, 20);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0.25");
        jPanel7.add(jTextField2);
        jTextField2.setBounds(80, 60, 70, 20);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0.25");
        jPanel7.add(jTextField3);
        jTextField3.setBounds(220, 30, 70, 20);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0.25");
        jPanel7.add(jTextField4);
        jTextField4.setBounds(220, 60, 70, 20);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0.25");
        jPanel7.add(jTextField5);
        jTextField5.setBounds(80, 30, 70, 20);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(10, 70, 330, 100);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 110, 350, 180);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " VWCA Parameters ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel5.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Weighting Factors ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel10.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setText("W1 :");
        jPanel10.add(jLabel21);
        jLabel21.setBounds(10, 20, 50, 20);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setText("W3 :");
        jPanel10.add(jLabel22);
        jLabel22.setBounds(10, 60, 60, 20);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setText("W2 :");
        jPanel10.add(jLabel23);
        jLabel23.setBounds(10, 40, 60, 20);

        vw1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vw1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vw1.setText("0.25");
        jPanel10.add(vw1);
        vw1.setBounds(80, 20, 70, 20);

        vw2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vw2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vw2.setText("0.25");
        jPanel10.add(vw2);
        vw2.setBounds(80, 40, 70, 20);

        vw3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vw3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vw3.setText("0.25");
        jPanel10.add(vw3);
        vw3.setBounds(80, 60, 70, 20);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setText("W4 :");
        jPanel10.add(jLabel24);
        jLabel24.setBounds(10, 80, 60, 20);

        vw4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vw4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vw4.setText("0.25");
        jPanel10.add(vw4);
        vw4.setBounds(80, 80, 70, 20);

        jPanel5.add(jPanel10);
        jPanel10.setBounds(10, 70, 170, 110);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Abnormality Factors ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel11.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel32.setText("e2 :");
        jPanel11.add(jLabel32);
        jLabel32.setBounds(90, 20, 30, 20);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel34.setText("e1 :");
        jPanel11.add(jLabel34);
        jLabel34.setBounds(10, 20, 30, 20);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0.6");
        jPanel11.add(jTextField10);
        jTextField10.setBounds(40, 20, 40, 20);

        jTextField14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("0.4");
        jPanel11.add(jTextField14);
        jTextField14.setBounds(120, 20, 40, 20);

        jPanel5.add(jPanel11);
        jPanel11.setBounds(10, 20, 170, 45);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Density Factors ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel12.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setText("Dl :");
        jPanel12.add(jLabel31);
        jLabel31.setBounds(20, 20, 65, 20);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel36.setText("Lav :");
        jPanel12.add(jLabel36);
        jLabel36.setBounds(20, 40, 65, 20);

        DL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DL.setText("35");
        jPanel12.add(DL);
        DL.setBounds(80, 20, 60, 20);

        LAV.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LAV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LAV.setText("4");
        jPanel12.add(LAV);
        LAV.setBounds(80, 40, 60, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel16.setText("m");
        jPanel12.add(jLabel16);
        jLabel16.setBounds(150, 20, 20, 20);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel35.setText("m");
        jPanel12.add(jLabel35);
        jLabel35.setBounds(150, 40, 20, 20);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel33.setText("Nbr. Avg:");
        jPanel12.add(jLabel33);
        jLabel33.setBounds(20, 60, 65, 20);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("R Avg.:");
        jPanel12.add(jLabel17);
        jLabel17.setBounds(20, 80, 65, 20);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel29.setText("RtMax :");
        jPanel12.add(jLabel29);
        jLabel29.setBounds(20, 100, 65, 20);

        rtmax.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rtmax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rtmax.setText("1000");
        jPanel12.add(rtmax);
        rtmax.setBounds(80, 100, 60, 20);

        jTextField12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("150");
        jPanel12.add(jTextField12);
        jTextField12.setBounds(80, 80, 60, 20);

        jTextField13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("300");
        jPanel12.add(jTextField13);
        jTextField13.setBounds(80, 60, 60, 20);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel37.setText("m");
        jPanel12.add(jLabel37);
        jLabel37.setBounds(150, 80, 20, 20);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel30.setText("m");
        jPanel12.add(jLabel30);
        jLabel30.setBounds(150, 100, 30, 20);

        jPanel5.add(jPanel12);
        jPanel12.setBounds(180, 20, 170, 130);

        jLabel38.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel38.setText("Density (K) :");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(190, 150, 70, 20);

        densite.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        densite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        densite.setText("0.8");
        jPanel5.add(densite);
        densite.setBounds(260, 150, 60, 20);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(370, 300, 360, 190);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " WCA Parameters ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel6.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Weights ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel9.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Weight of Connectivity Degre (W1) :");
        jPanel9.add(jLabel18);
        jLabel18.setBounds(10, 20, 210, 20);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setText("Weight of Relative Mobility (W3) :");
        jPanel9.add(jLabel19);
        jLabel19.setBounds(10, 60, 220, 20);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setText("Weight of Medium Relative Distance (W2) :");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(10, 40, 220, 20);

        w1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        w1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        w1.setText("0.25");
        jPanel9.add(w1);
        w1.setBounds(240, 20, 70, 20);

        w2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        w2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        w2.setText("0.10");
        jPanel9.add(w2);
        w2.setBounds(240, 40, 70, 20);

        w3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        w3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        w3.setText("0.65");
        jPanel9.add(w3);
        w3.setBounds(240, 60, 70, 20);

        jPanel6.add(jPanel9);
        jPanel9.setBounds(10, 70, 320, 100);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Size of Group :");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(20, 30, 110, 20);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("5");
        jPanel6.add(jTextField9);
        jTextField9.setBounds(250, 30, 70, 20);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 300, 350, 190);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Network Parameters ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel8.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel9.setText("Range of transmission of Ca :");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(30, 60, 170, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel10.setText("m");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(280, 60, 40, 20);

        rt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rt.setText("200");
        jPanel8.add(rt);
        rt.setBounds(210, 20, 60, 20);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel25.setText("Range of transmission of car :");
        jPanel8.add(jLabel25);
        jLabel25.setBounds(30, 20, 170, 20);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel26.setText("Range of transmission of Rsu :");
        jPanel8.add(jLabel26);
        jLabel26.setBounds(30, 40, 170, 20);

        rc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rc.setText("1500");
        jPanel8.add(rc);
        rc.setBounds(210, 60, 60, 20);

        rr.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rr.setText("1000");
        jPanel8.add(rr);
        rr.setBounds(210, 40, 60, 20);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel27.setText("m");
        jPanel8.add(jLabel27);
        jLabel27.setBounds(280, 20, 40, 20);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel28.setText("m");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(280, 40, 40, 20);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(10, 12, 350, 90);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        Adhoc.lambda   = Double.parseDouble(lambda.getText().toString());

        //NTN.setText(""+ps.nbObj);
        Adhoc.tsim     = Integer.parseInt(Tsim.getText().toString());
        Adhoc.avi       = Integer.parseInt(jTextField1.getText());
        
        Adhoc.portee    = Integer.parseInt(rt.getText())*10;
        Adhoc.porteeMax = Integer.parseInt(rtmax.getText())*10;
        
        Adhoc.porteeRSU = Integer.parseInt(rr.getText())*10;
        Adhoc.porteeCA  = Integer.parseInt(rc.getText())*10;
        
        
        Adhoc.alpha   = Double.parseDouble(jTextField5.getText());
        Adhoc.beta   = Double.parseDouble(jTextField2.getText());
        Adhoc.gamma   = Double.parseDouble(jTextField3.getText());
        Adhoc.sigma   = Double.parseDouble(jTextField4.getText());
        
        
        Algorithms.APROVE.lambdaAPROV      = Double.parseDouble(jTextField6.getText().toString().trim());
        
        Algorithms.APROVE.Iter             = Integer.parseInt(jTextField7.getText());
        Algorithms.APROVE.Th               = Integer.parseInt(jTextField8.getText().toString().trim());
        
        
        Adhoc.K    = Integer.parseInt(jTextField9.getText().toString());
        
        Adhoc.w1   = Double.parseDouble(w1.getText());
        Adhoc.w2   = Double.parseDouble(w2.getText());
        Adhoc.w3   = Double.parseDouble(w3.getText());
        
        Adhoc.vw1  = Double.parseDouble(vw1.getText());
        Adhoc.vw2  = Double.parseDouble(vw2.getText());
        Adhoc.vw3  = Double.parseDouble(vw3.getText());        
        Adhoc.vw4  = Double.parseDouble(vw3.getText());
        
        Adhoc.NbAvg = Double.parseDouble(jTextField13.getText().toString());
        Adhoc.Ravg  = Double.parseDouble(jTextField12.getText().toString());
        Adhoc.rtMax = Double.parseDouble(rtmax.getText().toString());
        
        Adhoc.Nv    = Adhoc.NbAvg/Adhoc.Ravg;
        Adhoc.Phi   = rnd.nextDouble()*(Adhoc.Nv-1);
        Adhoc.sig   = Math.exp(Adhoc.Phi);
        
        Adhoc.e1  = Double.parseDouble(jTextField10.getText().toString());
        Adhoc.e2  = Double.parseDouble(jTextField14.getText().toString());
        
        Adhoc.Dl  = Double.parseDouble(DL.getText().toString());
        Adhoc.Lav  = Double.parseDouble(LAV.getText().toString());
        Adhoc.Nl   = 3;
        Adhoc.Nt = Adhoc.Nl* (200.0/(Adhoc.Dl + Adhoc.Lav));
        Adhoc.density = Double.parseDouble(densite.getText().toString());
        
     this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Param.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Param.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Param.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Param.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Param().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DL;
    private javax.swing.JTextField LAV;
    private javax.swing.JTextField Tsim;
    private javax.swing.JTextField densite;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lambda;
    private javax.swing.JTextField rc;
    private javax.swing.JTextField rr;
    private javax.swing.JTextField rt;
    private javax.swing.JTextField rtmax;
    private javax.swing.JTextField vw1;
    private javax.swing.JTextField vw2;
    private javax.swing.JTextField vw3;
    private javax.swing.JTextField vw4;
    private javax.swing.JTextField w1;
    private javax.swing.JTextField w2;
    private javax.swing.JTextField w3;
    // End of variables declaration//GEN-END:variables
}
